### ISSUE TITLE
Fix flakey test

### ISSUE THREAD

**Issue by stevengill** [slackapi/node-slack-sdk#1165]
### Description

CI is failing randomly due to a flakey test in interactive-messages package.

```
1) SlackMessageAdapter
       #dispatch()
         when dispatching a message attachment action request
           should handle the callback returning a promise that fails before the timeout with a synchronous response:
     Error: Timeout of 50ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/node-slack-sdk/node-slack-sdk/packages/interactive-messages/src/adapter.spec.js)
      at runNextTicks (internal/process/task_queues.js:58:5)
      at processTimers (internal/timers.js:494:9)




lerna ERR! npm run test stderr:
(node:3497) UnhandledPromiseRejectionWarning: Error: test error
    at delayed (/home/runner/work/node-slack-sdk/node-slack-sdk/packages/interactive-messages/test/helpers.js:96:13)
    at SlackMessageAdapter.<anonymous> (/home/runner/work/node-slack-sdk/node-slack-sdk/packages/interactive-messages/src/adapter.spec.js:653:18)
    at SlackMessageAdapter.dispatch (/home/runner/work/node-slack-sdk/node-slack-sdk/packages/interactive-messages/src/adapter.ts:95:78)
    at Context.<anonymous> (/home/runner/work/node-slack-sdk/node-slack-sdk/packages/interactive-messages/src/adapter.spec.js:655:41)
    at callFn (/home/runner/work/node-slack-sdk/node-slack-sdk/node_modules/mocha/lib/runnable.js:387:21)
    at Test.Runnable.run (/home/runner/work/node-slack-sdk/node-slack-sdk/node_modules/mocha/lib/runnable.js:379:7)
    at Runner.runTest (/home/runner/work/node-slack-sdk/node-slack-sdk/node_modules/mocha/lib/runner.js:535:10)
    at /home/runner/work/node-slack-sdk/node-slack-sdk/node_modules/mocha/lib/runner.js:653:12
    at next (/home/runner/work/node-slack-sdk/node-slack-sdk/node_modules/mocha/lib/runner.js:447:14)
    at /home/runner/work/node-slack-sdk/node-slack-sdk/node_modules/mocha/lib/runner.js:457:7
    at next (/home/runner/work/node-slack-sdk/node-slack-sdk/node_modules/mocha/lib/runner.js:362:14)
    at /home/runner/work/node-slack-sdk/node-slack-sdk/node_modules/mocha/lib/runner.js:420:7
    at done (/home/runner/work/node-slack-sdk/node-slack-sdk/node_modules/mocha/lib/runnable.js:334:5)
    at callFn (/home/runner/work/node-slack-sdk/node-slack-sdk/node_modules/mocha/lib/runnable.js:410:7)
    at Hook.Runnable.run (/home/runner/work/node-slack-sdk/node-slack-sdk/node_modules/mocha/lib/runnable.js:379:7)
    at next (/home/runner/work/node-slack-sdk/node-slack-sdk/node_modules/mocha/lib/runner.js:384:10)
    at Immediate.<anonymous> (/home/runner/work/node-slack-sdk/node-slack-sdk/node_modules/mocha/lib/runner.js:425:5)
    at processImmediate (internal/timers.js:461:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3497) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3497) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @slack/interactive-messages@2.0.0 test: `nyc mocha --config .mocharc.json src/*.spec.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @slack/interactive-messages@2.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-01-26T01_08_00_936Z-debug.log

lerna ERR! npm run test exited 1 in '@slack/interactive-messages'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `lerna run test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-01-26T01_08_00_994Z-debug.log
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [x] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/interactive-messages`

**Comment by aoberoi** [comment]
I wasn't able to reproduce this issue locally, but here's my theory of what's going on:

The test is set to timeout at 50ms. The delayed promise it creates is meant to resolve in __at least__ 5ms. In most cases, the event loop is available enough (not running other tasks/microtasks) to allow the delayed promise to complete well before the 50ms deadline. However since `delayed()` is implemented using `setTimeout()`, the Promise can get delayed quite a bit if the event loop is busy. This might be happening on under-resourced systems like the CI processes in GitHub Actions.

The fix I implemented is alter `delayed()` to use `setImmediate()` instead of `setTimeout()` when the time is set to 0. And then I also made the flaky test use a 0ms delay so that it falls under the new condition. `setImmediate()` doesn't get queued behind quite as much in the runtime, so it has the opportunity to execute much sooner. When `delayed()` is called with 0, what that really means is we want the Promise to resolve as soon as possible. That's what this implementation acheives.

**Comment by seratch** [comment]
@aoberoi @stevengill 
Sadly, the situation arised again after merging #1169 -  https://github.com/slackapi/node-slack-sdk/runs/1829372237

As we already announced the deprecation of the package [here](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6), we don't need to spend more time to seek the fundamental solution for this. How about increasing the timeout as a workaround?

**Comment by aoberoi** [comment]
Darn! It's a different test that failed. We could increase the timeout, or it might be just as easy to use `delayed(0, ...)` to gain the quicker Promise resolution to fix this one. I haven't even read the test case yet but I can take a quick look.

**Comment by aoberoi** [comment]
Okay I think increasing the timeout as @seratch suggested is the best approach for this failed test case.

**Comment by seratch** [comment]
Increased the timeout value by the commit https://github.com/slackapi/node-slack-sdk/commit/8b46a960a0bd1036a13870d21ecea5fb64873d13

We can revisit this issue if we still see the occasional test failures.
