### ISSUE TITLE
Modal responses for interactive-endpoint

### ISSUE THREAD

**Issue by hckhanh** [slackapi/node-slack-sdk#909]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [X] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---
I cannot use Interactive URL to response the form error for `view_submission`

![image](https://user-images.githubusercontent.com/6380436/68986591-79faaa80-0853-11ea-8a76-3f3074a08619.png)

I write the api for interactive url in Lambda, then I set the interactive url and submit the form. I always receive this error on the view modal:
```
We had some trouble connecting. Try again?
```

The response for `view_submission` event that is requested to my server
```js
{
  response_action: "errors",
    errors: {
      "restaurant-name": "You may not select a due date in the past"
    }
}
```

**Comment by hckhanh** [comment]
By the way, the document is not good. It does not detailed

**Comment by hckhanh** [comment]
I don't know the error details, and I don't know how I can fix it. It's so hopeless :(

**Comment by seratch** [comment]
How about making sure if your Lambda function really received the requests by checking CloudWatch logs? 

I'm not sure what your situation is but there are several possible patterns:
* The requests from Slack servers may be sent to another endpoint (make sure if the request url is correct again)
* Your endpoint may not be available or reachable from Slack servers
* Your endpoint doesn't return 200 OK to requests from Slack servers

**Comment by hckhanh** [comment]
@seratch, I mean when I make an action on Slack, Slack make the requst by using the interactive url I provided in the app's settings. My Server receive the request from Slack and send back to Slack the response like this:
```
{
  response_action: "errors",
    errors: {
      "restaurant-name": "You may not select a due date in the past"
    }
}
```

With status code: 200

**Comment by hckhanh** [comment]
But  I always receive:
```
We had some trouble connecting. Try again?
```

But when I try to send the empty `body`, it close the modal view with no error
```
200 OK
{}
```

**Comment by seratch** [comment]
I see. Does your modal have the restaurant-name?

**Comment by aoberoi** [comment]
Just to be clear, your handler is **returning** the object you've shown above, right? And as @seratch mentioned, `"restaurant-name"` is the `block_id` of the block which contains the input element, right?

Let's also try to make sure it isn't timing out. Can you [follow the instructions for debugging](https://slack.dev/node-slack-sdk/interactive-messages#debugging), and let us know what you see in the logs?

**Comment by hckhanh** [comment]
@seratch My modal has a block with id `restaurant-name`. Is it right?
@aoberoi Here is the log

```
@slack/interactive-messages:adapter instantiated +0ms
@slack/interactive-messages:http-handler request received - method: POST, path: / +0ms
@slack/interactive-messages:http-handler Parsing raw request +1ms
@slack/interactive-messages:http-handler request signing verification success +3ms
@slack/interactive-messages:adapter dispatching to handler +2s
```

**Comment by hckhanh** [comment]
Here is my modal

```
{
  "type": "modal",
  "callback_id": "create-form",
  "title": {
    "type": "plain_text",
    "text": "Tạo thực đơn",
    "emoji": true
  },
  "submit": {
    "type": "plain_text",
    "text": "Tạo menu",
    "emoji": true
  },
  "close": {
    "type": "plain_text",
    "text": "Hủy",
    "emoji": true
  },
  "blocks": [
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": "Vui lòng *điền đầy đủ* thông tin bên dưới để tạo thực đơn:"
      }
    },
    {
      "type": "input",
      "block_id": "restaurant-name",
      "element": {
        "type": "plain_text_input",
        "placeholder": {
          "type": "plain_text",
          "text": "Quán Cơm 321"
        }
      },
      "label": {
        "type": "plain_text",
        "text": "Tên nhà hàng/quán ăn",
        "emoji": true
      }
    },
    {
      "type": "input",
      "block_id": "restaurant-menu",
      "element": {
        "type": "plain_text_input",
        "multiline": true,
        "placeholder": {
          "type": "plain_text",
          "text": "Tên món ăn 1|Đơn giá\nTên món ăn 2|Đơn giá\nTên món ăn 3|Đơn giá"
        }
      },
      "label": {
        "type": "plain_text",
        "text": "Danh sách món ăn",
        "emoji": true
      }
    }
  ]
}

```

**Comment by hckhanh** [comment]
This is the viewSubmission handler

```
slackInteractions.viewSubmission("create-form", payload => {
 return Promise.resolve({
    response_action: "errors",
    errors: { "restaurant-name": "You may not select a due date in the past" }
  });
});
```

**Comment by hckhanh** [comment]
It's amazing. Now It works like a charm ✌️

**Comment by aoberoi** [comment]
Okay that’s great news. We’ve narrowed the problem down to usage with AWS Lambda. I haven’t used this package on Lambda before but you might find the information here helpful: https://github.com/slackapi/node-slack-sdk/issues/896

**Comment by dannyshaw** [comment]
I'm having random lambda issues also. This is a very vague untested theory:

I _think_ the issue is thinking about the lambda as a server that can just keep running and processing async callbacks. I believe slack operates by both allowing responses to the initial request, but also posting of new messages to a specific `response_url` after returning a blank 200 to the initial request.

As Lambda kills the running instance as soon as you return from it. there's no continuing on and then making another call to the `response_url` as a traditional server would do.  I think perhaps we need to trigger a new lambda somehow to do that. I'm not sure it's possible with `interactive-messages`

Again this is just a hunch.

**Comment by lemonbakeoff** [comment]
Has anyone ever confirmed this?

I think @dannyshaw is right.

Anyone come up with a workaround?

**Comment by SurabhiHariharan** [comment]
Hello all, Any confirmed answers for this post?. Im facing the same issue as mentioned here. Im using a model which collects data and sends to my redirect url and i could process the data. But when i try to validate the data and send error response back to slack, nothing happens except the error we had some trouble connecting. My response looks like something like this
{
  "response_action": "errors",
  "errors": {
    "date-block": "You may not select a future date"
  }
}
And im using golang for my slack app. Any help is welcome. Thanks in advance

**Comment by an-dev** [comment]
+1 on the above, getting the following error 

```
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] must provide an object [json-pointer:/view]']}}
```

with a payload of

```
{
	"type": "modal",
        "response_action": "errors",
        "errors": {
                "block_test": "lol"
        },
	"title": {
		"type": "plain_text",
		"text": "Notification settings",
		"emoji": true
	},
	"submit": {
		"type": "plain_text",
		"text": "Submit",
		"emoji": true
	},
	"close": {
		"type": "plain_text",
		"text": "Cancel",
		"emoji": true
	},
	"blocks": [
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*<fakelink.toUrl.com|PR Strategy 2019> posts into <fakelink.toChannel.com|#public-relations>*\n\nSelect which notifications to send:"
			}
		},
                {
			"type": "input",
                        "block_id": "block_test"
			"element": {
				"type": "plain_text_input"
			},
			"label": {
				"type": "plain_text",
				"text": "Label",
				"emoji": true
			}
		}
	]
}
```

**Comment by seratch** [comment]
@lemonbakeoff
Yes, as @dannyshaw mentioned, when running apps on AWS Lambda (or any other FaaS), developers should be aware of the possibility of termination of app containers once apps return an HTTP response to Slack. https://github.com/slackapi/bolt/issues/361 and https://github.com/slackapi/bolt/issues/395 are related to this topic and illustrate how we recognize this issue.

The available solutions are: 
1) have a queue to store messages from Slack and run another lambda function that takes and processes those messages asynchronously (the function can use response_url).
2) use [Bolt for JS](https://github.com/slackapi/bolt/)'s `processBeforeResponse: true` option and await `say`, `respond`, etc. (I know you're not using Bolt but Bolt for this use case is much easier)

```js
const app = new App({
  signingSecret: process.env.SLACK_SIGNING_SECRET,
  token: process.env.SLACK_BOT_TOKEN,
  processBeforeResponse: true,
});

app.command("/hellol", async ({ respond, ack }) => {
  await respond("What's up?"); // posts a message using response_url
  await ack(); // returns 200 OK after response_url call completion
});
```

@an-dev 
The JSON structure your app sends is invalid. You can use [Block Kit Builder (Modal Preview)](https://api.slack.com/tools/block-kit-builder?mode=modal) as a handy way to validate your payloads [this way](https://api.slack.com/tools/block-kit-builder?mode=modal&view=%7B%22type%22%3A%22modal%22%2C%22title%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22My%20App%22%2C%22emoji%22%3Atrue%7D%2C%22submit%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Submit%22%2C%22emoji%22%3Atrue%7D%2C%22close%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Cancel%22%2C%22emoji%22%3Atrue%7D%2C%22blocks%22%3A%5B%7B%22type%22%3A%22section%22%2C%22text%22%3A%7B%22type%22%3A%22mrkdwn%22%2C%22text%22%3A%22Hello%2C%20Assistant%20to%20the%20Regional%20Manager%20Dwight!%20*Michael%20Scott*%20wants%20to%20know%20where%20you%27d%20like%20to%20take%20the%20Paper%20Company%20investors%20to%20dinner%20tonight.%5Cn%5Cn%20*Please%20select%20a%20restaurant%3A*%22%7D%7D%2C%7B%22type%22%3A%22divider%22%7D%2C%7B%22type%22%3A%22section%22%2C%22text%22%3A%7B%22type%22%3A%22mrkdwn%22%2C%22text%22%3A%22*Farmhouse%20Thai%20Cuisine*%5Cn%3Astar%3A%3Astar%3A%3Astar%3A%3Astar%3A%201528%20reviews%5Cn%20They%20do%20have%20some%20vegan%20options%2C%20like%20the%20roti%20and%20curry%2C%20plus%20they%20have%20a%20ton%20of%20salad%20stuff%20and%20noodles%20can%20be%20ordered%20without%20meat!!%20They%20have%20something%20for%20everyone%20here%22%7D%2C%22accessory%22%3A%7B%22type%22%3A%22image%22%2C%22image_url%22%3A%22https%3A%2F%2Fs3-media3.fl.yelpcdn.com%2Fbphoto%2Fc7ed05m9lC2EmA3Aruue7A%2Fo.jpg%22%2C%22alt_text%22%3A%22alt%20text%20for%20image%22%7D%7D%2C%7B%22type%22%3A%22section%22%2C%22text%22%3A%7B%22type%22%3A%22mrkdwn%22%2C%22text%22%3A%22*Kin%20Khao*%5Cn%3Astar%3A%3Astar%3A%3Astar%3A%3Astar%3A%201638%20reviews%5Cn%20The%20sticky%20rice%20also%20goes%20wonderfully%20with%20the%20caramelized%20pork%20belly%2C%20which%20is%20absolutely%20melt-in-your-mouth%20and%20so%20soft.%22%7D%2C%22accessory%22%3A%7B%22type%22%3A%22image%22%2C%22image_url%22%3A%22https%3A%2F%2Fs3-media2.fl.yelpcdn.com%2Fbphoto%2Fkorel-1YjNtFtJlMTaC26A%2Fo.jpg%22%2C%22alt_text%22%3A%22alt%20text%20for%20image%22%7D%7D%2C%7B%22type%22%3A%22section%22%2C%22text%22%3A%7B%22type%22%3A%22mrkdwn%22%2C%22text%22%3A%22*Ler%20Ros*%5Cn%3Astar%3A%3Astar%3A%3Astar%3A%3Astar%3A%202082%20reviews%5Cn%20I%20would%20really%20recommend%20the%20%20Yum%20Koh%20Moo%20Yang%20-%20Spicy%20lime%20dressing%20and%20roasted%20quick%20marinated%20pork%20shoulder%2C%20basil%20leaves%2C%20chili%20%26%20rice%20powder.%22%7D%2C%22accessory%22%3A%7B%22type%22%3A%22image%22%2C%22image_url%22%3A%22https%3A%2F%2Fs3-media2.fl.yelpcdn.com%2Fbphoto%2FDawwNigKJ2ckPeDeDM7jAg%2Fo.jpg%22%2C%22alt_text%22%3A%22alt%20text%20for%20image%22%7D%7D%2C%7B%22type%22%3A%22divider%22%7D%2C%7B%22type%22%3A%22actions%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22button%22%2C%22text%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Farmhouse%22%2C%22emoji%22%3Atrue%7D%2C%22value%22%3A%22click_me_123%22%7D%2C%7B%22type%22%3A%22button%22%2C%22text%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Kin%20Khao%22%2C%22emoji%22%3Atrue%7D%2C%22value%22%3A%22click_me_123%22%7D%2C%7B%22type%22%3A%22button%22%2C%22text%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Ler%20Ros%22%2C%22emoji%22%3Atrue%7D%2C%22value%22%3A%22click_me_123%22%7D%5D%7D%5D%7D).

The valid one should be [like this](https://api.slack.com/tools/block-kit-builder?mode=modal&view=%7B%22type%22%3A%22modal%22%2C%22title%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22My%20App%22%2C%22emoji%22%3Atrue%7D%2C%22submit%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Submit%22%2C%22emoji%22%3Atrue%7D%2C%22close%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Cancel%22%2C%22emoji%22%3Atrue%7D%2C%22blocks%22%3A%5B%7B%22type%22%3A%22section%22%2C%22text%22%3A%7B%22type%22%3A%22mrkdwn%22%2C%22text%22%3A%22*%3Cfakelink.toUrl.com%7CPR%20Strategy%202019%3E%20posts%20into%20%3Cfakelink.toChannel.com%7C%23public-relations%3E*%5Cn%5CnSelect%20which%20notifications%20to%20send%3A%22%7D%7D%2C%7B%22type%22%3A%22input%22%2C%22block_id%22%3A%22block_test%22%2C%22element%22%3A%7B%22type%22%3A%22plain_text_input%22%7D%2C%22label%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Label%22%2C%22emoji%22%3Atrue%7D%7D%5D%7D).

Regarding the errors response, it is not supposed to be merged into the view. Your app sends only the following JSON data as an HTTP response to a `view_submission`typed  request from Slack. Refer to the official document for details: https://api.slack.com/surfaces/modals/using#displaying_errors

```json
{
  "response_action": "errors",
  "errors": {
    "block_test": "lol"
  }
}
```

**Comment by an-dev** [comment]
@seratch Thanks for your insight. I assumed the error response was to be merged with the existing modal template as the documentation isn't explicit about it being separate.

**Comment by gterras** [comment]
@seratch regarding your Bolt example :

```js
app.command("/hellol", async ({ respond, ack }) => {
  await respond("What's up?"); // posts a message using response_url
  await ack(); // returns 200 OK after response_url call completion
});
```

Does it still mean the logic done before ack has to to be done under 3 seconds ?

**Comment by stevengill** [comment]
@gterras yes it does. It is a limitation of the current design but most use cases should be able to complete within that timeframe. Are you running into issues with it?

**Comment by gterras** [comment]
I get occasional ack fails on Cloudrun which is expected to be sometimes slow (cold start, instance creation etc). This or any random network error can delay the response.  This lead to a very unpredictable and confusing UX unfortunately (can click two times the same button, grey triangle popping etc) 

I fear that getting a response consistently under 3 seconds (actually less ?) is not possible for anyone who built an app following [traditional Slack guidelines about events response](https://api.slack.com/events-api#receiving_events), even if the processing logic is simple. There are too much factors and the risk is too high. The queue system seems the only reasonable things to do then, but what does `processBeforeResponse` actually do then ?

**Comment by gterras** [comment]
FYI after discussion with my cloud team we concluded that by nature a Slack app is incompatible with FaaS core concepts (can't guarantee a cold start + request processing in less than 3s). Moving the app to AppEngine seems much more reasonable (same range of prices, container always up) and allow repositionning the ack at the top of listeners like a standard Slack app.

**Comment by stevengill** [comment]
@gterras `processBeforeResponse` allows your logic to run before `ack` is called. We found that calling `ack`, lambda would terminate because a response was sent and it wouldn't get to processing the logic. With `processBeforeResponse`, this was fixed.

IMO an always up solution is a better for slack apps, but we still want to support folks who want to use lambda (even though it has the limitations which you correctly mentioned).

**Comment by seratch** [comment]
I'm sure the team already provided answers (at least responses) to all the questions and comments (the original question about modals and general questions about cold-starts) in this issue.

Let me share some additional thoughts on the `processBeforeResponse` option. As already mentioned, the option is not a solution for 3 second timeout errors and/or general cold-start issues on FaaS. The option just guarantees all the code in a listener surely completes. For dealing with timeouts (due to long operations and cold-starts), you need to be a bit more creative.

Just for your information, we started offering lazy listener functions in [Bolt for Python](https://github.com/slackapi/bolt-python) as an experimental feature. To know what it is, refer to [the document](https://slack.dev/bolt-python/concepts#lazy-listeners) and [an example code](https://github.com/slackapi/bolt-python/blob/v0.9.2b0/examples/aws_lambda/lazy_aws_lambda.py). The feature is yet another way to realize the concept I proposed at https://github.com/slackapi/bolt-js/issues/361. It runs an asynchronous operation in another invocation of the same Lambda function with the same args (`body`, `context`, `say`, `respond`, and so on). The only difference is the async function is unable to call `ack()` method. This feature should be greatly helpful for building meaningful Slack apps on FaaS (or on-demand container services like Cloud Run). Developers can use this feature in addition to `process_before_response: True` option.

We haven't decided to implement the same feature in Bolt for JS yet in the short term. The concept may have some conflict with Bolt for JS's fundamental design concept - a listener is a sequential chain of middleware. So, at this point, our general recommendation is to go with some solution that enables you to store messages in a queue (say, SQS) plus to run another function that subscribes the queue asynchronously.

Thanks for writing in and sharing your thoughts here! If you would like to discuss the FaaS topic further, please feel free to create a discussion issue in bolt-js project like https://github.com/slackapi/bolt-js/issues/361.

**Comment by MrYoda** [comment]
Had the same issue with `We had some trouble connecting. Try again?`. I has sent valid (as I thought) json response with HTTP 200.
I'm using Python 3, flask & flask-restplus. After few hours I discovered that restplus extends response object with `message` field by default - really bad idea for Slack responses.

**Comment by dsuresh-ap** [comment]
Not sure if people are still having this issue but we had it with Azure functions. Turns out we needed to pass the content-type as `application/json` in the response. Hopefully that helps someone else.

**Comment by diegoandresdiazespinoza** [comment]
I had similar issues, the issue in my case was sending a 200 http but with some text. So for example I was sending 
`Response("OK", status_code=200)` and should be `Response("", status_code=200)`, reading carefully docs it state it 
[](https://api.slack.com/surfaces/modals#close_all_views)
